export const popupProfile = document.querySelector('.popup_profile'); //сам блок попап редактирования профиля
export const editButton = document.querySelector('.profile__edit-button'); //копка редактирования профиля
export const closeButton = document.querySelector('.popup__close-button'); //кнопка закрытия редактирования профиля
export const profileFormElement = document.querySelector('.popup__content_profile'); //форма редактирования профиля
export const nameInput = profileFormElement.querySelector('.popup__form_input_name'); //вводимое в форму имя, для профиля
export const jobInput = profileFormElement.querySelector('.popup__form_input_job'); //вводимое в форму занятие, для профиля
export const profilename = document.querySelector('.profile__name'); //имя отображаемое в профиле
export const profilejob = document.querySelector('.profile__job'); //занятие отображаемое в профиле
export const elements = document.querySelector('.elements'); //блок сайта для добавление карточек
export const addButton = document.querySelector('.profile__add-button'); //кнопка добавить картинку, которая в профиле
export const popupCard = document.querySelector('.popup_card'); //сам блок добавления карточки, попап
export const cardFormElement = document.querySelector('.popup__content_card'); //форма добавление карточки, попап
export const cardCloseButton = document.querySelector('#popupCardCloseButton'); //кнопка закрытия попапа добавления карточки
export const cardName = cardFormElement.querySelector('#formCardName'); //вводимое в форму название картинки, для добавления карточки
export const cardUrl = cardFormElement.querySelector('#formCardUrl'); //вводимый в форму URL картинки, для добавления карточки
export const popupImage = document.querySelector('.popup_image'); //сам блок попап с почти фулл-скрин картинкой
export const popupImageClose = document.querySelector('#popupImageCloseButton'); //кнопка выхода из просмотра картинки
export const popups = Array.from(document.querySelectorAll('.popup_profile')); //массив попапов
export const forms = Array.from(document.querySelectorAll('.popup__content')); // массив форм
export const image = document.querySelector('.popup__image'); //картинка из попапа
export const imageText = document.querySelector('.popup__text'); //текст под картинкой из попапа